---
title: "Pk Variant Calling Workflow"
author: "Jacob Westaway"
date: "Last updated on `r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: 1
  html_document:
    df_print: paged
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# About.
 - This workflow is for further development/testing of our Pk variant calling pipeline being run on National Computer Infrastructure's HPC Gadi.


# 01_QC_&_TRIM

File(s):  
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/01_QC_Trim/01_QC_Trim_batch*.pbs

Version(s): 
fastqc/0.11.7, parallel/20191022, multiqc/1.9, python3/3.8.5, TrimGalore/0.6.6 & cutadapt/3.5.

Submission: 
Several scripts with several samples per script (functions exectuted using loops).

Notes: 
Need to have the "paired" argument of trim_galore at the end, despite what the documentation says.
Next was quality and adaptor trimming, which was executed with [Trim_Galore](https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md), a wrapper around Cutadapt and FastQC written by Felix Krueger.
Trim_Galore was used in combination with [GNU parallel](https://www.gnu.org/software/parallel/parallel_tutorial.html), which is needed to handle the multiple file inputs.

    -j16 - threads
    --xapply - runs each pair (if not included then Trim_Galore will run every combination)
    --illumina - illumina adapters to be removed in trimming
    --fastqc  - trim_galore to perform QC on trimmed files
    --paired - paired (forward and reverse) file input
    ::: - specifies input files to parallel

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N QC_Trim
#PBS -j oe
#PBS -m ae
#PBS -l walltime=24:00:00,mem=50GB,jobfs=50GB,ncpus=16
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Create paths to required software or load modules"
module load fastqc/0.11.7
module load parallel/20191022 
module load multiqc/1.9 
module load python3/3.8.5
export PATH=$PATH:/g/data/pq84/bin/TrimGalore-0.6.6/ # trim galore wrapper for fastq and cutadapt
export PATH=$PATH:/home/588/jw1542/.local/bin # cutadapt_3.5 installed here
echo "---------------------------------------"
echo 'Change to working directory' 
cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria

echo "---------------------------------------"
echo "Set environment variable"
QC_OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/01_QC_Trim/fastqc"
TRIM_OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/01_QC_Trim/trimmed_fastq"

echo "---------------------------------------"
echo "Unzip batch"
unzip -j "data/batch2.zip" "batch2/*/PK_SB_DNA_00*fq.gz" -d "data/fastq"

echo "---------------------------------------"
echo "QC"
fastqc -t 20 -o $QC_OUTDIR data/fastq/*.fq.gz
multiqc $QC_OUTDIR/. -o $QC_OUTDIR

echo "---------------------------------------"
echo "Trim"
parallel -j16 --xapply trim_galore --illumina --fastqc -o $TRIM_OUTDIR --paired ::: data/fastq/*1.fq.gz ::: data/fastq/*2.fq.gz

echo "---------------------------------------"
echo "QC on Trimmed"
multiqc $TRIM_OUTDIR/. -o $TRIM_OUTDIR

echo "---------------------------------------"
echo "Clean up"
rm -f data/*fq.gz

echo "---------------------------------------"
echo "Finished"
```


# 02_MAPPING

File(s): 
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/02_Pk_mapping/batch*/Template.pbs

Version(s): 
samtools/1.12 & bwa/0.7.17 

Submission: 
PBS job for each sample. Create a Template.pbs file and sample_names.txt file, and then run the following:
for i in $(cat sample_names.txt); do sed s/SAMPLE/$i/g Template.pbs > ${i}.pbs; done
for file in *L4.pbs; do qsub $file; done

Notes:
Need to sort output from BWA by the read name (this is not compatible with indexing of the BAM file but is required for subsequent steps).
Reference genome must be indexed - can use `bwa index -p PKA1H1_index -a is strain_A1_H.1.Icor.fasta`.

BWA 
    M - Mark shorter split hits as secondary (for Picard compatibility).
    R - Complete read group header line. ’\t’ can be used in STR and will be converted to a TAB in the output SAM/BAM. The read group ID will be attached to every read in the output. An example is ’@RG\tID:foo\tSM:bar’. 

Samtools view 
    u - Output uncompressed BAM. This option saves time spent on compression/decompression and is thus preferred when the output is piped to another samtools command.
    S - sam file compatibility.

Samtools sort 
    n - Sort by name.
    o - Write final sorted output to FILE (rather than standard output).

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N Align_to_Pk
#PBS -j oe
#PBS -m ae
#PBS -l walltime=12:00:00,mem=20GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths to bwa and samtools"
module load samtools/1.12  
module load bwa/0.7.17 

echo "---------------------------------------"
echo 'Change to working directory' 
cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/01_QC_Trim/trimmed_fastq

echo "---------------------------------------"
echo 'Set environment vars'
OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/02_Mapping"
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
mkdir $OUTDIR

echo "---------------------------------------"
echo 'Exectue alignment with bwa to hg and sort to bam'

bwa mem -t 10 -M -R "@RG\tID:SAMPLE\tPL:ILLUMINA" $INDEXTDIR SAMPLE_1_val_1.fq.gz SAMPLE_2_val_2.fq.gz | samtools view -u -S - | samtools sort -n -o $OUTDIR/SAMPLE.bam

echo "---------------------------------------"
echo "Finsihed!"
```

# 03_BAM PRE PROCESSING

File(s):  
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/03_Bam_pre-processing/batch*/Template.pbs

Version(s): 
java/jdk-8.40 & samtools/1.12 & GATK/3.8.1

Submission:
PBS job for each sample.

Notes:

Why GATK have removed indel realignment from their software - https://github.com/broadinstitute/gatk-docs/blob/master/blog-2012-to-2019/2016-06-21-Changing_workflows_around_calling_SNPs_and_indels.md?id=7847
Why we decide to use GATK3 so that we can include it - "These changes are about improving efficiency in the face of incremental returns." & "influences should be subtle for high quality data but make a difference for lower quality data" - although QC suggests our data is high quality we cannot always gurantee that this will be the case and we want these incremental returns in accruacy. There appears to be no problem including indel realignment, except efficiency, and I am willing to sacrifice this (to an extent) to get peace of mind and reduce the potential for false positive mismatches around indels, in turn improving the base quality scrore recalibration.
Poor quality data without indel realignment should result in regions with poor mapping quality post BQSR where variants cannot be called. But if the quality is still above the threshold for variant calling, you could call false positive variants. So, the hope of GATK is that BQSR will catch the misaligned reads and minimise the number of false positives, and that with greater read quality and depth (~ x30) you are more likely to pick up on a poorly aligned read that will end up having a poor BQSR score that can be ignored. Obviously, this is less likely to be the case if you have lower quality or depth, and you can still end up with some false positives. This is what needs to be weighed up - efficiency vs quality. Thus, I think the decision should be made case by case, and in our case, where are working in the context of discovery with little to no need to scale, I think we want to guarantee quality.

To download GATK 3.8 - `wget https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef.tar.bz2`

GATK requires that the reference genome has .dict and .fai files:
  'java -jar picard.jar CreateSequenceDictionary R=strain_A1_H.1.Icor.fasta'
  'samtools faidx strain_A1_H.1.Icor.fasta'

GATK is run through Java, which requires compatible [jdk and jre](https://www.guru99.com/difference-between-jdk-jre-jvm.html#:~:text=The%20full%20form%20of%20JDK%20is%20Java%20Development,also%20platform%20dependent%2C%20but%20JVM%20is%20platform%20independent. installations).
Java uses a [Picard](https://github.com/broadinstitute/picard) jar file to run GATK.


GATK does not provide support for previous iterations of their software, so any additional information required needs to be obtained using `--help`.
Arguments:
  - T - GATK tool
  - intervals - genomic intervals (i.e. contigs and their base positon - BED file)
  - known - known **indels** - VCF file
  - knownsites - known **variants** - VCF file
  - consensusDeterminationModel - model for computing possible alternates - KNOWNS_ONLY uses known indels only
  - LOD - threshold for cleaning above
  - ERC - mode for emitting experimental reference confidence scores 
  - minPruning - minimum allowed pruning factor in assembly graph - paths with < x supporting kmers are pruned for the graph
  - maxNumHaplotypesInPopulation - self explanatory - number needs to be increased when calling organisms with high heterozygosity
  - variant_index_type - type of index creator
  - variant_index_parameter - to be passed to the VCF index creator
  - contamination - fraction of contamination in seq data to aggresively remove 
  - G - annotation
  - hets - heterozygosity value to be used to compute likelihoods 
  - indelHeterozygosity - heterozygosity value to be used for variant calling

Calculate approximate heterozygosity (needed for -hets and -indelHeterozygosity arguments):

Approximate heterozygosity = ((number of sites with Indels)/(Total number of sites))*(1-(average number of homozygous genotypes per site)/(total number of individuals))

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N Bam_pre-pro
#PBS -j oe
#PBS -m ae
#PBS -l walltime=12:00:00,mem=50GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load java/jdk-8.40 
module load samtools/1.12 

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'

INDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/02_Mapping"
OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/03_Bam-pre"
PICARD="/g/data/pq84/bin/picard/build/libs/picard.jar"
GATK="/g/data/pq84/bin/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar"
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
INTERVALS="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/strain_A1_H.1.Icor.fasta.bed"
KNOWNSITES="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/variants"

echo "---------------------------------------"
echo 'Sort and Index bam files'

cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/02_Mapping
mkdir sorted

samtools sort -@ 10 SAMPLE.bam > sorted/SAMPLE.sorted.bam
samtools index -@ 10 sorted/SAMPLE.sorted.bam

echo "---------------------------------------"
echo 'MarkDuplicates'

java -Djava.iodir=$PBS_JOBFS -jar $PICARD \
    MarkDuplicates AS=TRUE VALIDATION_STRINGENCY=LENIENT \
    I=$INDIR/sorted/SAMPLE.sorted.bam \
    O=$OUTDIR/SAMPLE.dupmarked.bam \
    M=$OUTDIR/SAMPLE_picard_metrics_file.txt 

echo "---------------------------------------"
echo 'Change header @RG and index' 

samtools view -H $OUTDIR/SAMPLE.dupmarked.bam | \
    sed 's,^@RG.*,@RG\tID:SAMPLE\tSM:SAMPLE\tLB:None\tPL:Illumina,g' |  \
    samtools reheader - $OUTDIR/SAMPLE.dupmarked.bam > $OUTDIR/SAMPLE.dupmarked.reheader.bam

samtools index $OUTDIR/SAMPLE.dupmarked.reheader.bam 

echo "---------------------------------------"
echo 'RealignerTargetCreator'

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T RealignerTargetCreator \
    -nt 10 \
    -R $INDEXTDIR \
    -I $OUTDIR/SAMPLE.dupmarked.reheader.bam \
    --intervals $INTERVALS \
    -known $KNOWNSITES/TRUE_INDELs.vcf \
    -o $OUTDIR/SAMPLE.dupmarked.realigner.intervals

echo "---------------------------------------"
echo 'IndelRealigner' 

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T IndelRealigner \
    --consensusDeterminationModel KNOWNS_ONLY \
    -LOD 0.4 \
    -R $INDEXTDIR \
    -I $OUTDIR/SAMPLE.dupmarked.reheader.bam \
    --intervals $INTERVALS \
    -known $KNOWNSITES/TRUE_INDELs.vcf \
    -targetIntervals $OUTDIR/SAMPLE.dupmarked.realigner.intervals \
    -o $OUTDIR/SAMPLE.dupmarked.realigned.bam

echo "---------------------------------------"
echo 'BaseRecalibrator - create recal table' 

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T BaseRecalibrator \
    -R $INDEXTDIR \
    -I $OUTDIR/SAMPLE.dupmarked.realigned.bam \
    --intervals $INTERVALS \
    -knownSites $KNOWNSITES/TRUE_consensus.vcf \
    -o $OUTDIR/SAMPLE.dupmarked.realigned.recal.table

echo "---------------------------------------"
echo 'PrintReads - get recal reads' 

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK  \
    -T PrintReads \
    -R $INDEXTDIR \
    --intervals $INTERVALS \
    -I $OUTDIR/SAMPLE.dupmarked.realigned.bam \
    -BQSR $OUTDIR/SAMPLE.dupmarked.realigned.recal.table \
    -o $OUTDIR/final_bam/SAMPLE.dupmarked.realigned.recal.bam

echo "---------------------------------------"
echo 'Clean up' 

rm -f $OUTDIR/SAMPLE.dupmarked.b*
rm -f $OUTDIR/SAMPLE.dupmarked.realigned.recal.table
rm -f $OUTDIR/SAMPLE.dupmarked.realigned.b* 
rm -f $OUTDIR/SAMPLE.dupmarked.realigner.intervals
rm -f $OUTDIR/SAMPLE.dupmarked.reheader.b*
rm -f $OUTDIR/SAMPLE_picard_metrics_file.txt 

echo "---------------------------------------"
echo 'Finished' 
```

# 04_VARIANT_CALLING 

## GATK

### HAPLOTYPE CALLER

File(s):  
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/04_Variant_calling/batch*/Template.pbs

Version(s): 
java/jdk-8.40 & & GATK/3.8.1

Submission:
PBS job for each sample.

Notes:
 - nt - number of threads
 - ERC - mode for emitting reference confidence scores
 - minPruning - the number of samples that must pass the pruning threshold
 - maxNumHaplotypesInPopulation - each haplotype considered requires n evaluations if there are n reads across all samples, so this argument defines a specific number to control this. Dropping this too low can result in missing variants.
 - max_alternate_alleles - maximum number of alternate alleles to genotype
 - contamination - fraction of contamination in sequencing data to aggresively remove. If > 0, the caller will remove contamination through biased down sampling of the reads
 - variant_index_type LINEAR & variant_index_parameter 128000 - old dodgey workaround that GATK used for index compression. Newer versions no longer need this 

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N Haplotype_call
#PBS -j oe
#PBS -m ae
#PBS -l walltime=12:00:00,mem=50GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load java/jdk-8.40 

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/haplotype_call"
INDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/03_Bam-pre/final_bam"
PICARD="/g/data/pq84/bin/picard/build/libs/picard.jar"
GATK="/g/data/pq84/bin/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar"
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
INTERVALS="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/strain_A1_H.1.Icor.fasta.bed"

echo "---------------------------------------------------------------------------------------------------------------------"
echo "GATK"
echo "---------------------------------------------------------------------------------------------------------------------"
java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T HaplotypeCaller \
    -ERC GVCF \
    --minPruning 3 \
    --maxNumHaplotypesInPopulation 200 \
    --max_alternate_alleles 3 \
    --variant_index_type LINEAR \
    --variant_index_parameter 128000 \
    -contamination 0.0 \
    -G Standard \
    -R $INDEXTDIR \
    -I $INDIR/SAMPLE.dupmarked.realigned.recal.bam \
    -o $OUTDIR/SAMPLE.dupmarked.realigned.recal.g.vcf.gz

echo "---------------------------------------------------------------------------------------------------------------------"
echo "FINISHED"
echo "---------------------------------------------------------------------------------------------------------------------"
```

### JOINT CALLING 

File(s):  
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/04_Variant_calling/batch*/gatk_variant_calling.pbs

Version(s): 
java/jdk-8.40 & & GATK/3.8.1

Submission: 
Single pbs script.

Notes:
`ls *gz | tr '\n' ' ' | sed 's/ / -V /g'` to get the file list

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N Variant_calling_gatk
#PBS -j oe
#PBS -m ae
#PBS -l walltime=12:00:00,mem=50GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load java/jdk-8.40 

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/gatk"
INDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/haplotype_call"
PICARD="/g/data/pq84/bin/picard/build/libs/picard.jar"
GATK="/g/data/pq84/bin/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar"
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
INTERVALS="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/strain_A1_H.1.Icor.fasta.bed"

cd $INDIR

echo "---------------------------------------------------------------------------------------------------------------------"
echo "Clean up VCF header"
echo "---------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------------------------------------------------------------------------------------"
echo "GATK"
echo "---------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------------------------------------------------------------------------------------"
echo "Combine GVCFs"

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T CombineGVCFs \
    -R $INDEXTDIR \
    -V PK_SB_DNA_004_DKDL210002133-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.g.vcf.gz -V PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.g.vcf.gz -V PK_SB_DNA_008_DKDL210002137-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.g.vcf.gz -V PK_SB_DNA_009_DKDL210002138-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.g.vcf.gz \
    -o $OUTDIR/GATK_combined.g.vcf.gz

echo "---------------------------------------------------------------------------------------------------------------------"
echo "Genotype GVCFs"

cd $OUTDIR

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T GenotypeGVCFs \
    -nt 10 \
    -R $INDEXTDIR \
    -L $INTERVALS \
    -V GATK_combined.g.vcf.gz \
    -o GATK_genotyped.vcf.gz

echo "---------------------------------------"
echo "Finished "
```

## BCFTOOLS

File(s):  
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/04_Variant_calling/batch*/bcftools_variant_calling.pbs

Version(s):
bcftools/1.12

Submission: 
Single PBS script.

Notes:
 - m - Alternative model for multiallelic and rare-variant calling
 - Oz - compressed output
 - a - annotate with the following parameters
 - v - variants only  

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N Variant_calling_bcftools
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=100GB,ncpus=21
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load bcftools/1.12

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/bcftools"
INDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/03_Bam-pre/final_bam"



echo "---------------------------------------------------------------------------------------------------------------------"
echo "create input bam file list"
echo "---------------------------------------------------------------------------------------------------------------------"
cd $INDIR

ls *bam | cut -d ' ' -f 10 > input_bam_files.list

echo "---------------------------------------------------------------------------------------------------------------------"
echo "bcftools"
echo "---------------------------------------------------------------------------------------------------------------------"

bcftools mpileup --threads 20 -f $INDEXTDIR -b $INDIR/input_bam_files.list \
   | bcftools call -m -Oz -a FORMAT/GQ,FORMAT/GP,INFO/PV4 -v -o $OUTDIR/bcftools_genotyped.vcf.gz

bcftools index --threads 20 -t -o $OUTDIR/bcftools_genotyped.vcf.gz.tbi $OUTDIR/bcftools_genotyped.vcf.gz

echo "---------------------------------------"
echo "Finished "

```

## CREATING A CONSENSUS VCF 

File(s):
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/04_Variant_calling/consensus_vcf.pbs

Version(s):
bcftools/1.12 & R/4.1.0 

Submission: 
Single PBS script.

Notes:
To intall packages on GADI - module load R/4.1.0 & module load intel-compiler/2021.5.0 - need a compiler. 
Need to specificy library - export R_LIBS_USER="/g/data/pq84/R"

  - bcftools query
    - f - format - inside the square brackets are for the annotation-specific column, whereas the annotations outside have their own column
  - fgrep 
    - f - file of patterns to search for

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N Variant_calling_consensus
#PBS -j oe
#PBS -m ae
#PBS -l walltime=24:00:00,mem=64GB,ncpus=16
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths"
module load bcftools/1.12
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
module load java/jdk-8.40  # new

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
PICARD="/g/data/pq84/bin/picard/build/libs/picard.jar"
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/consensus/"
INDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/"
GATK="/g/data/pq84/bin/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar" # new

cd $OUTDIR

echo "---------------------------------------------------------------------------------------------------------------------"
echo "Create consensus VCF"
echo "---------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'Merge variants from the two variant callers'
bcftools merge --threads 16 --force-samples -o $OUTDIR/merged_variants_only.vcf.gz $INDIR/GATK/GATK_genotyped.vcf.gz $INDIR/bcftools/bcftools_genotyped.vcf.gz

echo "---------------------------------------"
echo "Query VCF files to get a list of 'variant IDs' from each tool"
bcftools view merged_variants_only.vcf.gz | sed -n '/#CHROM/,$p' > merged_variants_only.tsv

echo "---------------------------------------"
echo "Execute R script - performs an inner join on the 'variant IDs' above to find the overlapping variants"
Rscript /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/04_Variant_calling/vcf_wrangle_2.R

echo "---------------------------------------"
echo "Create a seperate file that contains all the header information for the vcf"
bcftools view merged_variants_only.vcf.gz | sed '/#CHROM/q' > vcf_head.vcf

echo "---------------------------------------"
echo "Remove the column names from the variant names document to create a list of grep patterns"
tail -n +2 vcf_variant_names.tsv > grep_patterns.txt 

echo "---------------------------------------"
echo "Filter for variants from the original vcf that are called by both callers by using grep to match patterns created above" 
bcftools view merged_variants_only.vcf.gz | fgrep -f grep_patterns.txt - > filtered.vcf

echo "---------------------------------------"
echo "Concatenate the vcf header in the variants called by both callers"
cat vcf_head.vcf filtered.vcf > Consensus_with_duplicates.vcf

echo "---------------------------------------"
echo "Remove duplicate sample names from VCF"
java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T SelectVariants \
    -R $INDEXTDIR \
    -V Consensus_with_duplicates.vcf \
    -xl_se '2:' \
    -o Consensus.vcf
    
echo "---------------------------------------"
echo "Finished "
```

### R script nested in consensus PBS script

```{R,veal=F}
# Wrangle variant calling data - version 2 - using merged VCF file

# Load Packages
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(data.table)
library(tibble)

VCF <- read_tsv("/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/consensus/merged_variants_only.tsv", col_names = TRUE) %>% 
  rename("CHROM" = "#CHROM") %>% 
  mutate_at(1:5, as.factor) %>% 
  unite(variant_name, CHROM, POS, ID, REF, ALT, sep = "_") %>% 
  select(-c(2:5)) %>% 
  mutate_at(c(2:ncol(.)), ~str_remove(., ":.*")) %>% 
  mutate_at(c(2:ncol(.)), ~ifelse(. %like% "1/1", "1", .)) %>% # homozygous
  mutate_at(c(2:ncol(.)), ~ifelse(. %like% "1/0" | . %like% "0/1" , "0.5", .)) %>%  # heterozygous
  mutate_at(c(2:ncol(.)), ~ifelse(. != "1" & . != "0.5" , "0", .)) %>% 
  mutate(variant_name = str_remove(variant_name, "_\\.")) 

ordered_VCF <- VCF %>% 
  filter(grepl("ordered", variant_name)) %>% 
  select(1, starts_with("2:")) %>% 
  pivot_longer(!variant_name, names_to = "sample", values_to = "variant_1") %>% 
  mutate(sample = str_remove(sample, "2:")) %>% 
  left_join(
    VCF %>% 
      filter(grepl("ordered", variant_name)) %>% 
      select(1, !starts_with("2:")) %>% 
      pivot_longer(!variant_name, names_to = "sample", values_to = "variant_2")
  ) %>% 
  mutate_at(c(3:4), as.numeric) %>% 
  mutate(consensus_variant = ifelse((variant_1 == variant_2) & (variant_1 + variant_2 >= 1), 1, 0)) %>%
  filter(consensus_variant == 1) %>% 
  select(1,2,5) %>% 
  pivot_wider(names_from = sample, values_from = consensus_variant) %>%  
  select(1) %>%  
  separate(variant_name, into = c("X1", "X2", "X3", "X4", "POS", "REF", "ALT"), sep = "_") %>%  
  unite(CHROM, starts_with("X")) %>% 
  add_column(ID = ".") %>% 
  relocate(CHROM, POS, ID)  

MIT_VCF <- VCF %>% 
  filter(grepl("MIT", variant_name)) %>% 
  select(1, starts_with("2:")) %>% 
  pivot_longer(!variant_name, names_to = "sample", values_to = "variant_1") %>% 
  mutate(sample = str_remove(sample, "2:")) %>% 
  left_join(
    VCF %>% 
      filter(grepl("MIT", variant_name)) %>% 
      select(1, !starts_with("2:")) %>% 
      pivot_longer(!variant_name, names_to = "sample", values_to = "variant_2")
  ) %>% 
  mutate_at(c(3:4), as.numeric) %>% 
  mutate(consensus_variant = ifelse((variant_1 == variant_2) & (variant_1 + variant_2 >= 1), 1, 0)) %>%
  filter(consensus_variant == 1) %>% 
  select(1,2,5) %>% 
  pivot_wider(names_from = sample, values_from = consensus_variant) %>%  
  select(1) %>%  
  separate(variant_name, into = c("X1", "X2", "X3", "POS", "REF", "ALT"), sep = "_") %>%  
  unite(CHROM, starts_with("X")) %>% 
  add_column(ID = ".") %>% 
  relocate(CHROM, POS, ID)  

API_VCF <- VCF %>% 
  filter(grepl("API", variant_name)) %>% 
  select(1, starts_with("2:")) %>% 
  pivot_longer(!variant_name, names_to = "sample", values_to = "variant_1") %>% 
  mutate(sample = str_remove(sample, "2:")) %>% 
  left_join(
    VCF %>% 
      filter(grepl("API", variant_name)) %>% 
      select(1, !starts_with("2:")) %>% 
      pivot_longer(!variant_name, names_to = "sample", values_to = "variant_2")
  ) %>% 
  mutate_at(c(3:4), as.numeric) %>% 
  mutate(consensus_variant = ifelse((variant_1 == variant_2) & (variant_1 + variant_2 >= 1), 1, 0)) %>%
  filter(consensus_variant == 1) %>% 
  select(1,2,5) %>% 
  pivot_wider(names_from = sample, values_from = consensus_variant) %>%  
  select(1) %>%  
  separate(variant_name, into = c("X1", "X2", "X3", "X4", "X5", "POS", "REF", "ALT"), sep = "_") %>%  
  unite(CHROM, starts_with("X")) %>% 
  add_column(ID = ".") %>% 
  relocate(CHROM, POS, ID)  

ordered_VCF %>% 
  rbind(MIT_VCF, API_VCF) %>% 
  write_tsv("/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/consensus/vcf_variant_names.tsv")


```

# 05_VARIANT_FILTERING

File(s):  
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/05_Variant_filtering/Filter_variants.pbs

Version(s):
java/jdk-8.40 & & GATK/3.8.1

Submission:
Single PBS script.

Notes:
These filtering parameters are based on those appalied to *P. vivax* by the Sanger Institute, but with the values adjusted for the distribution of quality scrores in our truth set.

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N Filter_variants
#PBS -j oe
#PBS -m ae
#PBS -l walltime=12:00:00,mem=50GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load java/jdk-8.40 

echo "---------------------------------------"
echo "Define paths and change to working directory"
PICARD="/g/data/pq84/bin/picard/build/libs/picard.jar"
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
GATK="/g/data/pq84/bin/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar"
INDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/consensus/"
OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/filtered/"

cd $INDIR

echo "---------------------------------------"
echo 'Correct bcftools introduced changes to make java happy'
echo "---------------------------------------"
cat Consensus.vcf | sed 's/MQ=nan/MQ=NaN/g' > Consensus_fixed.vcf

echo "---------------------------------------"
echo 'SUBSET TO VARIANT TYPE'
echo "---------------------------------------"

echo "---------------------------------------"
echo "SNPs"

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T SelectVariants \
    -R $INDEXTDIR \
    -V Consensus_fixed.vcf \
    -selectType SNP \
    -o $OUTDIR/GVCFall_SNPs.vcf

echo "---------------------------------------"
echo "Indels"

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T SelectVariants \
    -R $INDEXTDIR \
    -V Consensus_fixed.vcf \
    -selectType INDEL \
    -o $OUTDIR/GVCFall_INDELs.vcf

echo "---------------------------------------"
echo 'FILTER'
echo "---------------------------------------"

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T VariantFiltration \
    -V $INDIR/Consensus_fixed.vcf \
    -R $INDEXTDIR \
    -filter "QD < 20.0" -filterName "QD2" \
    -filter "FS > 2.0" -filterName "FS60" \
    -filter "MQ < 59.0" -filterName "MQ40" \
    -o $OUTDIR/PK_consensus_FILTERED.vcf

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T VariantFiltration \
    -V $OUTDIR/GVCFall_SNPs.vcf \
    -R $INDEXTDIR \
    -filter "QD < 20.0" -filterName "QD2" \
    -filter "FS > 2.0" -filterName "FS60" \
    -filter "MQ < 59.0" -filterName "MQ40" \
    -o $OUTDIR/FILTERED_SNPs.vcf

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T VariantFiltration \
    -V $OUTDIR/GVCFall_INDELs.vcf \
    -R $INDEXTDIR \
    -filter "QD < 20.0" -filterName "QD2" \
    -filter "FS > 2.0" -filterName "FS60" \
    -filter "MQ < 59.0" -filterName "MQ40" \
    -o $OUTDIR/FILTERED_INDELs.vcf

echo "---------------------------------------"
echo "Finsihed"

```

# 06_VARIANT_ANNOTATION

File(s):  
/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/pipeline/06_Variant_annotation/annotate_variants.pbs

Version(s):
perl/5.26 & ensembl vep/105.0

Submission:
Single PBS script.

Notes:

Installing vep:
    - GitHub URL: https://github.com/Ensembl/ensembl-vep
    - To install vep on Gadi requires a gcc compiler, but the Annobin requirement is not installed and must be done so before using gcc to compile vep.
    - Also require PERL to install cpanM, which can then be used to install the Perl libraries needed by vep.

We first needed to modify our GFF file:
    - Change the contig names to match the reference genome and VCF files.
    - Substitute protein_coding_gene for gene.
    - Sort and modfiy the structure to suit ensembl requirements.

Script:

```{R,eval=F}
#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N Annotate_variants
#PBS -j oe
#PBS -m ae
#PBS -l walltime=12:00:00,mem=80GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
export PATH=$PATH:/g/data/pq84/bin/ensembl-vep

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
INDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/filtered/"
OUTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/05_Variant_annotation"
GFF="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/gff/updated_version"
FASTA="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"

cd $INDIR

echo "---------------------------------------------------------------------------------------------------------------------"
echo "SNPs"
vep -i FILTERED_SNPs.vcf --gff $GFF/PlasmoDB-55_PknowlesiA1H1.gff.gz --fasta $FASTA -o $OUTDIR/SNP_variant_annotation.txt --force_overwrite --everything

echo "---------------------------------------------------------------------------------------------------------------------"
echo "INDELs"
vep -i FILTERED_INDELs.vcf --gff $GFF/PlasmoDB-55_PknowlesiA1H1.gff.gz --fasta $FASTA -o $OUTDIR/Indel_variant_annotation.txt --force_overwrite --everything

echo "---------------------------------------"
echo "FINISHED"
```